
name: AliveWater Monitor
on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 5 минут
  workflow_dispatch:       # Разрешить ручной запуск

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-driver sqlite3
          pip install selenium webdriver-manager telebot
          
      - name: Run monitoring
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: |
          python monitor.py
          
      - name: Upload database backup
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: subscribers-db-backup
          path: subscribers.db
