name: AliveWater Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager telebot python-dotenv

      - name: Create .env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "LOGIN=${{ secrets.LOGIN }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> .env

      - name: Run monitoring
        run: |
          python monitor.py
