name: Water Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # Запускать каждые 5 минут
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium webdriver-manager telebot
    
    - name: Run monitor
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python monitor.py
