name: AliveWater Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate token
        run: |
          if [[ -z "${{ secrets.BOT_TOKEN }}" || "${{ secrets.BOT_TOKEN }}" != *:* ]]; then
            echo "::error::Invalid BOT_TOKEN format! Should be like 123456789:ABCdef..."
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-driver
          pip install selenium webdriver-manager telebot python-dotenv

      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: |
          python monitor.py
